config/routes.rb
Contacts::Application.routes.draw do
  devise_for :user

  resources :contacts, only: [:index, :show]

  root :to => 'contacts#index'

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :state
	belongs_to :city

	def complete_name
		first_name + ' ' + last_name
	end
end

app/models/state.rb
class State < ActiveRecord::Base
	has_many :cities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	before_filter :authenticate_user!

	def index
		@contacts = Contact.all
	end

	def show
		@contact = Contact.find params[:id]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/index.html.erb
<div class='pull-right'>
	<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
</div>

<h2>Contacts</h2>
<ul>
	<% @contacts.each do |contact| %>
		<li>
			<%= link_to contact.complete_name, contact_path(contact)%>
		</li>
	<% end %>
</ul>

app/views/contacts/show.html.erb
<div class='pull-right'>
	<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
</div>

<dl class="dl-horizontal">	
	<dt>First Name</dt>
	<dd><%= @contact.first_name %></dd>
	<dt>Last Name</dt>
	<dd><%= @contact.last_name %></dd>
	<dt>Company</dt>
	<dd><%= @contact.company_name %></dd>
	<dt>Address</dt>
	<dd><%= @contact.address %></dd>
	<dt>City</dt>
	<dd><%= @contact.city.name %></dd>
	<dt>County</dt>
	<dd><%= @contact.county %></dd>
	<dt>State</dt>
	<dd><%= @contact.state.name %></dd>
	<dt>Phone 1</dt>
	<dd><%= @contact.phone1 %></dd>
	<dt>Phone 2</dt>
	<dd><%= @contact.phone2 %></dd>
	<dt>Email</dt>
	<dd><%= @contact.email %></dd>
	<dt>Web</dt>
	<dd><%= link_to @contact.web, @contact.web, :target => "_blank" %></dd>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contacts</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>